name: release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Build
        run: go build -trimpath -ldflags "-s -w -H windowsgui" -o gotool.exe .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gotool
          path: gotool.exe

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: gotool.exe
